### ISSUE TITLE
Python 3.9 Support

### ISSUE THREAD

**Issue by aidandunlop** [sky-uk/kfp-operator#160]
**Is your feature request related to a problem? Please describe.**
When using Python 3.9, training pipelines fail to compile when deploying to KFP with the KFP Operator. [The TFX Penguin pipeline example](https://www.tensorflow.org/tfx/tutorials/tfx/penguin_simple) can run locally using `tfx.orchestration.LocalDagRunner` with 3.9, but fails when using a KFP Operator Pipeline resource which points to a training pipeline using Python 3.9:
```
update-pipeline-mhrmm-1212883284: time="2022-09-06T09:06:07.972Z" level=info msg="capturing logs" argo=true
update-pipeline-mhrmm-1212883284: 2022-09-06 09:06:11.088639: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
update-pipeline-mhrmm-1212883284: 2022-09-06 09:06:11.088681: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
update-pipeline-mhrmm-1212883284: Traceback (most recent call last):
update-pipeline-mhrmm-1212883284:   File "/shared/compile.py", line 3, in <module>
update-pipeline-mhrmm-1212883284:     from kfp_compiler.compiler import main
update-pipeline-mhrmm-1212883284:   File "/shared/kfp_compiler/compiler.py", line 7, in <module>
update-pipeline-mhrmm-1212883284:     from tfx.orchestration.kubeflow import kubeflow_dag_runner
update-pipeline-mhrmm-1212883284:   File "/usr/local/lib/python3.9/site-packages/tfx/orchestration/kubeflow/kubeflow_dag_runner.py", line 27, in <module>
update-pipeline-mhrmm-1212883284:     from tfx.dsl.compiler import compiler as tfx_compiler
update-pipeline-mhrmm-1212883284:   File "/usr/local/lib/python3.9/site-packages/tfx/dsl/compiler/compiler.py", line 31, in <module>
update-pipeline-mhrmm-1212883284:     from tfx.dsl.input_resolution.ops import ops
update-pipeline-mhrmm-1212883284:   File "/usr/local/lib/python3.9/site-packages/tfx/dsl/input_resolution/ops/ops.py", line 22, in <module>
update-pipeline-mhrmm-1212883284:     from tfx.dsl.input_resolution.strategies import conditional_strategy
update-pipeline-mhrmm-1212883284:   File "/usr/local/lib/python3.9/site-packages/tfx/dsl/input_resolution/strategies/conditional_strategy.py", line 19, in <module>
update-pipeline-mhrmm-1212883284:     from tfx.dsl.compiler import placeholder_utils
update-pipeline-mhrmm-1212883284:   File "/usr/local/lib/python3.9/site-packages/tfx/dsl/compiler/placeholder_utils.py", line 33, in <module>
update-pipeline-mhrmm-1212883284:     from google.protobuf.pyext import _message
update-pipeline-mhrmm-1212883284: ImportError: cannot import name '_message' from 'google.protobuf.pyext' (/shared/google/protobuf/pyext/__init__.py)
update-pipeline-mhrmm-1212883284: time="2022-09-06T09:06:16.474Z" level=error msg="cannot save artifact /tmp/pipeline.yaml" argo=true error="stat /tmp/pipeline.yaml: no such file or directory"
update-pipeline-mhrmm-1212883284: Error: exit status 1
```

**Describe the solution you'd like**
Support for training pipelines using Python 3.9

**Describe alternatives you've considered**
- Use an older version of Python -  3.7 works as expected with the penguin pipeline, but users on 3.9 won't be able to use the KFP Operator. 
- Submit pipelines using 3.9 to KFP manually - but this won't allow users to reap the benefits of the KFP Operator

**Additional context**
The KFP Operator currently supports Python 3.7 (as the latest version of TFX only officially supports 3.7), so training pipelines should just use 3.7 when working with the KFP Operator for now. [Python 3.7 will be deprecated in 9 months](https://endoflife.date/python), so it's worth adding support for later versions of Python soon.

**Comment by rwbeauchemin** [comment]
Mentioning this issue on main TFX that led to us being able to do this just recently. Good arguments for removing technical debt there: https://github.com/tensorflow/tfx/issues/4797
